# Generated by Django 5.2.6 on 2025-10-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_anonymfeedbackmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymfeedbackmodel',
            options={'verbose_name': 'Анонимный отзыв', 'verbose_name_plural': 'Анонимные отзывы'},
        ),
        migrations.AlterModelOptions(
            name='identifiedfeedbackmodel',
            options={'verbose_name': 'Идентифицированный отзыв', 'verbose_name_plural': 'Идентифицированные отзывы'},
        ),
        migrations.AlterModelOptions(
            name='telegramusers',
            options={'verbose_name': 'Пользователи школы', 'verbose_name_plural': 'Пользователи школы'},
        ),
    ]
